version: '3.8'

services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: db_docker_symfony
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: challenge
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    networks:
      - dev

  php-fpm:
    container_name: php-fpm
    restart: unless-stopped
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - ./api/:/var/www
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./docker/nginx
    volumes:
      - ./api/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8741:80"
      - "443:443"
    networks:
      - dev

  vue-ui:
    image: node:19.2.0-alpine3.16
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    networks:
      - dev
      
networks:
    dev:
        driver: bridge

volumes:
    db:
<<<<<<< HEAD

=======
>>>>>>> c29c4913 (adding fix)

