version: '3.8'

services:
  db:
    image: mysql:8
    container_name: db_docker_symfony
    restart: always
    volumes:
        - db-data:/var/lib/mariadb
    environment:
        MYSQL_ROOT_PASSWORD: challenge
        MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    networks:
        - dev

  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - ./api/:/var/www

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
        - db
    ports:
        - 8082:80
    environment:
        PMA_HOST: db
    networks:
        - dev
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./api/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8741:80"
      - "443:443"

  vue-ui:
    image: node:19.2.0-alpine3.16
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
      
networks:
    dev:
volumes:
    db-data:


