version: '3'

services:
  database:
    image: mysql:8.0
    container_name: db_docker_symfony
    restart: always
    volumes:
        - db-data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: challenge
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    networks:
        - dev
        
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
        - database
    ports:
        - 8082:80
    environment:
        PMA_HOST: database
    networks:
        - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
        - dev

  www:
    build: ./api/php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
        - ./api/php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    networks:
        - dev

  vue-ui:
    image: node:19.2.0-alpine3.16
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
        - dev

networks:
    dev:
        driver: bridge

volumes:
    db-data:
    


