name: Build Docker Image

on:
  push:
    branches: ["feature/admin", "master", "develop"]

  pull_request:
    branches: ["feature/admin", "master", "develop"]

env:
  platforms: "linux/amd64, linux/arm64/v8"

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: frontend
          file: frontend/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/challenge-frontend:latest
          push: true
          platforms: ${{ env.platforms }}

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Start PostgreSQL container
        run : |
          docker run --name challenge -e POSTGRES_PASSWORD=password -d postgres

      - name: Build Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: api
          file: api/php/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/challenge-backend:latest
          push: true
          platforms: ${{ env.platforms }}