name: Build Docker Image

on:
  push:
    branches: ['features/ci-cd'],

  pull_request:
    branches: ['features/ci-cd'],

env:
  platforms: "linux/amd64, linux/arm64/v8"
  workdir_frontend: frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

      steps:
        - use: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci
          npm run build

deploy:
  runs-on: ubuntu-latest

  needs: build

  steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ env.platforms }}
        push: true
        tags: "frontend:latest"

    - name: Inspect
      run: docker inspect --format='{{index .RepoDigests 0}}' frontend:latest